name: Auto Backport Master to Develop

on:
  push:
    branches: [ master ]

jobs:
  backport:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Configure Git
      run: |
        git config --global user.name "Auto Backport Bot"
        git config --global user.email "bot@rutaslogisticas.com"
    
    - name: Auto Backport to Develop
      run: |
        echo "Iniciando backport automatico de master a develop..."
        
        # Obtener informacion del commit
        COMMIT_SHA=$(git rev-parse HEAD)
        COMMIT_TITLE=$(git log -1 --pretty=format:"%s")
        COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
        
        echo "Commit: $COMMIT_TITLE"
        echo "Autor: $COMMIT_AUTHOR"
        echo "SHA: $COMMIT_SHA"
        
        # Cambiar a develop y actualizar
        echo "Cambiando a rama develop..."
        git checkout develop
        git pull origin develop
        
        # Hacer cherry-pick del ultimo commit de master
        echo "Aplicando cherry-pick..."
        if git cherry-pick $COMMIT_SHA; then
          # Push del backport
          echo "Cherry-pick exitoso, haciendo push a develop..."
          git push origin develop
          
          echo "Backport completado exitosamente!"
          echo "master y develop estan sincronizados"
        else
          # Si hay conflictos, crear PR para resolver manualmente
          echo "Conflicto detectado, creando PR para resolucion manual..."
          
          # Crear PR usando GitHub CLI
          gh pr create \
            --title "Backport automatico - Resolucion de conflictos requerida" \
            --body "Backport automatico encontro conflictos. Commit: $COMMIT_SHA. Resolver conflictos y hacer merge." \
            --base develop \
            --head develop \
            --label "backport,conflict,needs-review"
            
          echo "PR creado para resolucion manual de conflictos"
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Notification
      if: always()
      run: |
        echo "Proceso de backport completado"
        echo "Estado: ${{ job.status }}"